import Head from 'next/head';
import Sidebar from '../components/Sidebar'



export default function Home() {
 
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/whatsapp.gif" />
      </Head>

    <Sidebar/>
    </div>
  )
}
